/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class character extends javax.swing.JPanel {

    /**
     * Creates new form character
     */
    public character() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssassinButton = new javax.swing.JButton();
        MageButton = new javax.swing.JButton();
        RangerButton = new javax.swing.JButton();
        WarriorButton = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        CharacterStatScreen = new javax.swing.JTextField();

        AssassinButton.setText("Assassin");
        AssassinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                assassin_mouseover(evt);
            }
        });
        AssassinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssassinButtonActionPerformed(evt);
            }
        });

        MageButton.setText("Mage");
        MageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mage_mouseover(evt);
            }
        });
        MageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MageButtonPerformed(evt);
            }
        });

        RangerButton.setText("Ranger");
        RangerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ranger_mouseover(evt);
            }
        });
        RangerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RangerButtonPerformed(evt);
            }
        });

        WarriorButton.setText("Warrior");
        WarriorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                warrior_mouseover(evt);
            }
        });
        WarriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarriorButtonPerformed(evt);
            }
        });

        Return.setText("Back");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonPerformed(evt);
            }
        });

        CharacterStatScreen.setText("No Charcter Chosen");
        CharacterStatScreen.setToolTipText("");
        CharacterStatScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharacterStatScreenUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(WarriorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RangerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AssassinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(CharacterStatScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Return)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Return)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AssassinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RangerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WarriorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                    .addComponent(CharacterStatScreen))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    //selects a class 
    private void AssassinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssassinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssassinButtonActionPerformed

    private void MageButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MageButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MageButtonPerformed

    private void RangerButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RangerButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RangerButtonPerformed

    private void WarriorButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarriorButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WarriorButtonPerformed

    
    //returns to main menu
    private void ReturnButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnButtonPerformed

    
    //When moused over, the button will display stats onto the characterstat screen
    private void assassin_mouseover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assassin_mouseover
        // TODO add your handling code here:
    }//GEN-LAST:event_assassin_mouseover

    private void mage_mouseover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mage_mouseover
        // TODO add your handling code here:
    }//GEN-LAST:event_mage_mouseover

    private void ranger_mouseover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ranger_mouseover
        // TODO add your handling code here:
    }//GEN-LAST:event_ranger_mouseover

    private void warrior_mouseover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_warrior_mouseover
        // TODO add your handling code here:
    }//GEN-LAST:event_warrior_mouseover

    
    //updates character screen once character mouseovered.
    
    private void CharacterStatScreenUpdate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharacterStatScreenUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterStatScreenUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssassinButton;
    private javax.swing.JTextField CharacterStatScreen;
    private javax.swing.JButton MageButton;
    private javax.swing.JButton RangerButton;
    private javax.swing.JButton Return;
    private javax.swing.JButton WarriorButton;
    // End of variables declaration//GEN-END:variables
}
