import Characters.*;
import java.util.*;
import Enemies.*;
        
public class Gameplay extends javax.swing.JFrame {

    /**
     * Creates new form Gameplay
     * @param characterClass
     */
    public static String CharacterClass;
    
    public Gameplay(String characterclass) {
        initComponents();
        CharacterClass = characterclass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        attackbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Display.setColumns(20);
        Display.setRows(5);
        jScrollPane1.setViewportView(Display);

        attackbtn.setText("Fight");
        attackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(attackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(attackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackbtnActionPerformed
        //if there is no enemy, the button will say fight, so we change text to Attack and create an enemy
        if(enemy == null){
            attackbtn.setText("Attack");
            createEnemy();
        } else{
            
        }
        
        
    }//GEN-LAST:event_attackbtnActionPerformed

    public static PlayableCharacter player;
    public static Enemies enemy;
    public static String enemytype;
    
    
    public static void createPlayer(){ 
        switch (CharacterClass) {
            case "Warrior":
                player = new Warrior();                
                break;
            case "Mage":
                player = new Mage();
                break;
            case "Ranger":
                player = new Ranger();
                break;
            case "Assassin":
                player = new Assassin();
                break;
            default:
                break;
        }
    }
    
    
    public static void createEnemy(){
        Random newEnemy = new Random();
        int n = newEnemy.nextInt(4);
        while (n==0){
            n = newEnemy.nextInt(4);
        }
        switch(n){
            case 1:
                enemy = new Bandit(player.getLevel());
                enemytype = "Bandit";
                break;
            case 2:
                enemy = new Kobold(player.getLevel());
                enemytype = "Kobold";
                break;
            case 3:
                enemy = new Goblin(player.getLevel());
                enemytype = "Goblin";
                break;
        }
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
        createPlayer();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Display;
    private javax.swing.JButton attackbtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
