
/**
 *
 * @author blake
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        startButton = new javax.swing.JButton();
        Assassinbtn = new javax.swing.JRadioButton();
        Magebtn = new javax.swing.JRadioButton();
        Warriorbtn = new javax.swing.JRadioButton();
        Rangerbtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        txtOutput.setText("        Welcome to Text RPG Extravaganza!\n     Select a character class to get started!");
        jScrollPane1.setViewportView(txtOutput);
        txtOutput.getAccessibleContext().setAccessibleName("");

        startButton.setLabel("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        BtnGroup.add(Assassinbtn);
        Assassinbtn.setText("Assassin");
        Assassinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssassinbtnActionPerformed(evt);
            }
        });

        BtnGroup.add(Magebtn);
        Magebtn.setText("Mage");
        Magebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagebtnActionPerformed(evt);
            }
        });

        BtnGroup.add(Warriorbtn);
        Warriorbtn.setText("Warrior");
        Warriorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarriorbtnActionPerformed(evt);
            }
        });

        BtnGroup.add(Rangerbtn);
        Rangerbtn.setText("Ranger");
        Rangerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RangerbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Warriorbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Assassinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rangerbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Magebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Magebtn)
                    .addComponent(Assassinbtn))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rangerbtn)
                    .addComponent(Warriorbtn))
                .addGap(18, 18, 18)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartScreen screen = new StartScreen();
                screen.setVisible(true);
            }
        });
    }
    
    private String CharacterClass;
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

       //finalize character selection to pass to next frame
       if(Assassinbtn.isSelected())
       {
           CharacterClass = "Assassin";
       }
       else if(Warriorbtn.isSelected())
       {
           CharacterClass = "Warrior";
       }
       else if(Magebtn.isSelected())
       {
           CharacterClass = "Mage";
       }
       else if(Rangerbtn.isSelected())
       {
           CharacterClass = "Ranger";
       }
       //switch to gameplay frame and pass class selection
       super.setVisible(false);
       Gameplay screen2 = new Gameplay(CharacterClass);
       screen2.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void AssassinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssassinbtnActionPerformed
        txtOutput.setText("Hp: 12");
        txtOutput.append("\nAttack Damage: 9");
    }//GEN-LAST:event_AssassinbtnActionPerformed

    private void MagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagebtnActionPerformed
        txtOutput.setText("Hp: 14");
        txtOutput.append("\nAttack Damage: 7");
    }//GEN-LAST:event_MagebtnActionPerformed

    private void WarriorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarriorbtnActionPerformed
        txtOutput.setText("Hp: 20");
        txtOutput.append("\nAttack Damage: 4");
    }//GEN-LAST:event_WarriorbtnActionPerformed

    private void RangerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RangerbtnActionPerformed
        txtOutput.setText("Hp: 16");
        txtOutput.append("\nAttack Damage: 6");
    }//GEN-LAST:event_RangerbtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Assassinbtn;
    private javax.swing.ButtonGroup BtnGroup;
    private javax.swing.JRadioButton Magebtn;
    private javax.swing.JRadioButton Rangerbtn;
    private javax.swing.JRadioButton Warriorbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startButton;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
