/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class character extends javax.swing.JPanel {

    /**
     * Creates new form character
     */
    public character() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Return = new javax.swing.JButton();
        CharacterStatScreen = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        Return.setText("Back");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonPerformed(evt);
            }
        });

        CharacterStatScreen.setText("No Charcter Chosen");
        CharacterStatScreen.setToolTipText("");
        CharacterStatScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharacterStatScreenUpdate(evt);
            }
        });

        jRadioButton1.setText("Assassin");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssassinButtonPerformed(evt);
            }
        });

        jRadioButton2.setText("Mage");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MageButtonPerformed(evt);
            }
        });

        jRadioButton3.setText("Ranger");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RangerButtonPerformed(evt);
            }
        });

        jRadioButton4.setText("Warrior");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarriorButtonPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(77, 77, 77)
                        .addComponent(CharacterStatScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Return)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Return)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addComponent(CharacterStatScreen))
                .addContainerGap())
        );

        jRadioButton4.getAccessibleContext().setAccessibleName("Warrior");
        jRadioButton4.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //returns to main menu
    private void ReturnButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnButtonPerformed

    
    
    
    
    private void CharacterStatScreenUpdate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharacterStatScreenUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterStatScreenUpdate

    //character select buttons
    
    private void AssassinButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssassinButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssassinButtonPerformed

    private void MageButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MageButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MageButtonPerformed

    private void RangerButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RangerButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RangerButtonPerformed

    private void WarriorButtonPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarriorButtonPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WarriorButtonPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CharacterStatScreen;
    private javax.swing.JButton Return;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
